### ISSUE TITLE
Make it possible to manage SELinux context for checks installed

### ISSUE THREAD

**Issue by rlaurika** [CSCfi/ansible-role-nrpe-plugins#4]
Occasionally it might be necessary to set the proper SELinux context for a check file so that executing a check doesn't run into permissions issues.

One example of a script with this issue is pynagsystemd.py:
https://github.com/kbytesys/pynagsystemd/blob/master/bin/pynagsystemd.py

Installing that script via pip and trying to execute it via check_nrpe while SELinux is enabled leads to a permission denied because the script can't run systemctl in a subprocess. If you put the pynagsystemd.py script into the same SELinux context as all other Nagios check scripts then it works just fine.

Since Ansible 2.2 this can be achieved with the sefcontext Ansible module:
http://docs.ansible.com/ansible/latest/sefcontext_module.html

**Comment by rlaurika** [comment]
Addressed by https://github.com/CSCfi/ansible-role-nrpe-plugins/pull/5

**Comment by martbhell** [comment]
Does #5 solve this? (It's merged and doesn't fail syntax checks but I have not actually tested it)

**Comment by rlaurika** [comment]
Yes - that PR solves this.
